import { Avatar, AvatarFallback, AvatarImage } from '../components/ui/avatar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from '../components/webcomponents/sidebar'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark p-4'>
      <body className={inter.className} >
        <div className="border-b ">
          <div className="flex h-16 items-center px-4 text-2xl font-bold">
            <Image 
            src="/images/album.png"
            alt="image"
            height="60"
            width="60"
            /> 
            ShahzadAKJ Photos
            <div className="ml-auto flex items-center space-x-4 ">
            <Avatar>
             <AvatarImage src="/images/avatar2.png" alt="@shadcn"/>
             <AvatarFallback>PG</AvatarFallback>
            </Avatar>
            </div>
          </div>
        </div>
        <div className='flex'>
        <Sidebar />
        <div className='px-6 py-3 w-full'>
        {children}
        </div>
       </div>
      </body>
    </html>
  )
}
